# Site settings
title: Ming Ti's website
email: elliotdots1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/test/" # the subpath of your site, e.g. /blog/
url: "https://minhtrimai.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: minhtrimai

# Build settings
markdown: kramdown
